---
title: "SEM Application (mroz)"
subtitle: "Labor market of married, Working Women"
---

## Case Description

Let's consider the labor market for married women already in the workforce.

We will use the data on working, married women in `wooldridge::mroz` to estimate the labor supply and wage demand equations 
by 2SLS. 

The full set of instruments includes `educ`, `age`, `kidslt6`, `nwifeinc`, `exper`, and `exper2`. 


## Models setting

### The structrual equations

$$
\begin{aligned}
\text { hours } & =\alpha_1 \log ( wage)+\beta_{10}+\beta_{11} { educ }+\beta_{12} age+\beta_{13}  { kidslt6 } &&\\
&+\beta_{14} { nwifeinc }+u_1  &&\text{(supply)}\\
 \log ({ wage }) &=\alpha_2 { hours }+\beta_{20}+\beta_{21} { educ }+\beta_{22} { exper }  +\beta_{23} { exper }^2+ u_2 && \quad \text{(demand)}
\end{aligned}
$$

- In the demand function, we write the wage offer as a function of hours and the usual productivity variables. 

- All variables except `hours` and `log(wage)` are assumed to be exogenous. 

- `educ` might be correlated with omitted `ability` in either equation. Here, we just ignore the omitted ability problem.

### The reduced equations

$$
\begin{alignedat}{8}
\text { hours } & =\pi_{10}+\pi_{11} { educ }+\pi_{12} age+\pi_{13}  { kidslt6 }  +\pi_{14} { nwifeinc }\\
&+\pi_{15} { exper }  +\pi_{16} {exper}^2 +v_1  \\
 \log ({ wage }) &=\pi_{20}+\pi_{21} { educ }+\pi_{22} age+\pi_{23}  { kidslt6 }  +\pi_{24} { nwifeinc } \\
 &+\pi_{25} { exper }  +\pi_{26} {exper}^2+ v_2
\end{alignedat}
$$

## Reproducible Sources

**Wooldridge, J.M. Introductory econometrics: a modern approach[M].** Seventh edition. Australia: Cengage, 2020.

- Example 16.5: labor Supply of married, Working Women

## Learning Targets

a. Understand the nature of `SEM`.

b. Know the steps of running TSLS method.

c. Be familiar with R package function `systemfit::systemfit()`.

## Exercise Materials 

You can find all the exercise materials in this project under the file directory:

```{r}
#| echo: false
# show files tree
fs::dir_tree(path = here::here("sem-wage-mroz"),
             recurse = 1)
```